# Generated by Django 5.1.1 on 2024-09-21 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kdapp', '0002_user_adress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='adress',
            field=models.JSONField(help_text='adres json '),
        ),
    ]
