# Generated by Django 5.1.1 on 2024-09-21 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kdapp', '0003_alter_user_adress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='adress',
            field=models.JSONField(default=dict, help_text='Adres bilgilerini JSON formatında giriniz.', null=True),
        ),
    ]
