# Generated by Django 5.1.1 on 2024-09-21 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kdapp', '0004_alter_user_adress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
