# Generated by Django 5.1.1 on 2024-09-21 01:53

import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kdapp', '0005_alter_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='company',
            field=models.JSONField(default=dict, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, default='N/A', max_length=17, null=True, region=None),
        ),
        migrations.AddField(
            model_name='user',
            name='website',
            field=models.CharField(default='N/A', max_length=100),
            preserve_default=False,
        ),
    ]
